# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('pub_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
