# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_code_discribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('url', models.TextField()),
                ('data', models.TextField(null=True)),
                ('type', models.TextField()),
                ('result', models.CharField(max_length=500)),
            ],
        ),
    ]
